//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIUniversities.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Career
    {
        public Career()
        {
            this.Courses = new HashSet<Cours>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string universityCode { get; set; }
    
        public virtual University University { get; set; }
        public virtual ICollection<Cours> Courses { get; set; }
    }
}
