//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIUniversities.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Universities
    {
        public Universities()
        {
            this.Careers = new HashSet<Careers>();
        }
    
        public string code { get; set; }
        public string name { get; set; }
        public string website { get; set; }
    
        public virtual ICollection<Careers> Careers { get; set; }
    }
}
